FROM dunglas/frankenphp:php8.5

ARG WWWUSER=1000
ARG WWWGROUP=1000

RUN groupadd -g ${WWWGROUP} dev && useradd -u ${WWWUSER} -g dev -m -s /bin/bash dev

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        nano \
        supervisor \
        ca-certificates \
        nodejs \
        npm \
        poppler-utils \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions \
        pdo_pgsql \
        redis \
        gd \
        intl \
        bcmath \
        zip \
        exif \
        pcntl \
        opcache

COPY Docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY Docker/php.ini /usr/local/etc/php/conf.d/90-custom.ini

RUN mkdir -p /var/log/supervisor \
    && chown -R dev:dev /var/www/html /var/log/supervisor

COPY --chmod=0755 Docker/supercronic /usr/bin/supercronic

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY Docker/entrypoint.sh /usr/local/bin/
RUN chmod 0755 /usr/local/bin/entrypoint.sh

USER dev

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/up || exit 1
